#!/usr/bin/env bash

function check_record {
    local domain="$1"
    local subdomain="$2"
    local record_type="$3"
    local destination=$(dig +short "${subdomain}.${domain}" "${record_type}" | tail -n 1)
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

if [ -z "$1" ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomains=("www" "lb-01" "web-01" "web-02")

if [ -n "$2" ]; then
    subdomains=("$2")
fi

for subdomain in "${subdomains[@]}"; do
    check_record "${domain}" "${subdomain}" "A"
done

