#!/usr/bin/env bash
# Configure my domain zone:
# www --> 914-lb-01 34.237.76.64
# web-01 --> 914-web-01 34.138.32.248
# web-02 --> 914-web-02 3.226.74.205

# -- To be evaluated --
# domain_information () {
#     line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
#     echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
# }

# if [ "$#" == 1 ]
# then
#   domain_information "$1" "www"
#   domain_information "$1" "lb-01"
#   domain_information "$1" "web-01"
#   domain_information "$1" "web-02"
# elif [ "$#" == 2 ]
# then
#   domain_information "$1" "$2"
# fi
#-- To be evaluated --

function check_record {
    local domain="$1"
    local subdomain="$2"
    local record_type="$3"
    local destination=$(dig +short "${subdomain}.${domain}" "${record_type}" | tail -n 1)
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

if [ -z "$1" ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomains=("www" "lb-01" "web-01" "web-02")

if [ -n "$2" ]; then
    subdomains=("$2")
fi

for subdomain in "${subdomains[@]}"; do
    check_record "${domain}" "${subdomain}" "A"
done

