#!/usr/bin/env bash

set -euo pipefail

function check_record {
    local domain="${1}"
    local subdomain="${2}"
    local record_type="${3}"
    local destination
    destination="$(dig +short "${subdomain}.${domain}" "${record_type}" | tail -n 1)"
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="${1}"
subdomains=("www" "lb-01" "web-01" "web-02")

if [[ $# -eq 2 ]]; then
    subdomains=("${2}")
fi

for subdomain in "${subdomains[@]}"; do
    check_record "${domain}" "${subdomain}" "A"
done 
