#!/usr/bin/env bash
#Install nginx on your web-01
#Nginx should be listening on port 80

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
killall nginx
nginx

