#!/usr/bin/env bash

# Install nginx
apt-get update -y
apt-get install nginx -y

# Configure nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx start
