#!/usr/bin/env bash

# Install nginx
apt-get update -y
apt-get install nginx -y

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;
    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default

service nginx restar 

