#!/usr/bin/env bash

# Update the package index and install Nginx
sudo apt update
sudo apt install nginx -y

# Configure the custom 404 error page
sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /usr/share/nginx/html;
        echo "Ceci n'est pas une page";
    }
}
EOF

# Restart Nginx to apply the changes
sudo systemctl restart nginx 

