#!/bin/bash

# Install HAproxy
sudo apt-get update && sudo apt-get install haproxy -y

# Configure HAproxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Test and restart HAproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart

