#!/bin/bash
# Configure Nginx to run and listen on port 80 of all the server's active IPv4 IPs
# Install Nginx

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart 
