#!/bin/bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Configure Nginx to listen on port 80 of all the server's active IPv4 IPs
sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;\n    listen \[::\]:80 default_server;/g' /etc/nginx/nginx.conf

# Restart Nginx
sudo systemctl restart nginx

