#!/usr/bin/env bash
# get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it
RUN echo "Hello Holberton" > /usr/local/apache2/htdocs/index.html
docker run -p 8080:80 -d my-apache-image 

